-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 02:49:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shutthebox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shutthebox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shutthebox` DEFAULT CHARACTER SET utf8 ;
USE `shutthebox` ;

-- -----------------------------------------------------
-- Table `shutthebox`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shutthebox`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `dtaNascimento` DATE NOT NULL,
  `tipoUser` INT NOT NULL DEFAULT 0,
  `estadoConta` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shutthebox`.`pontos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shutthebox`.`pontos` (
  `id_jogo` INT(11) NOT NULL AUTO_INCREMENT,
  `pontos` INT(11) NOT NULL,
  `users_id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_jogo`),
  INDEX `fk_pontos_users_idx` (`users_id_user` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
