<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use ArmoredCore\WebObjects\Post;

$idUser = Session::has("id_user");

if ($idUser == false) {
    View::make('jogo_stb.login');

}else{

$estadoContaUser = Session::has("tipoUser");

if ($estadoContaUser == true) {
$estadoContaUser2 = Session::get("tipoUser");

if ($estadoContaUser2 == 0){
    View::make('jogo_stb.index');
}else{


Layout::includeLayout('menu');

$servername = "localhost:3308";
$username = "root";
$password = "";
$dbname = "shutthebox";

try {
$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


$stmt = $conn->prepare("SELECT * FROM  users");
$stmt->execute();

?>

<div class="search-player justify-content-center">
    <form class="form-inline" method="post" action="<?= Url::toRoute('user/search') ?>">
        <input class="form-control mr-sm-2" name="search" type="text" placeholder="Search">
        <button class="btn btn-dark" type="submit">Search</button>
    </form>
</div>

<?php
$SearchId = Session::has('searchId');

if ($SearchId == True) {
    $search = Session::get('searchId');
    $stmtSearch = $conn->prepare("SELECT * FROM  users WHERE id_user = '$search'");
    $stmtSearch->execute();
}
?>

<div class="players-container">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col">ID User</th>
            <th scope="col">Username</th>
            <th scope="col">Banir</th>
        </tr>
        </thead>
        <tbody class="tbody">
        <?php
        if (Post::has('search')) {
            while ($lista = $stmtSearch->fetch(PDO::FETCH_ASSOC)) { ?>
                <tr>
                <th scope="row"><?= $lista["id_user"] ?></th>
                <td><?= $lista["username"] ?></td>
                <?php
                $estado_conta = $lista["estadoConta"];

                if ($estado_conta == 0) {

                    ?>
                    <td>
                        <a class="btn btn-dark my-2 my-sm-0" href="<?= URL::toRoute('user/banir', $lista["id_user"]) ?>"
                           role="button">Banir</a>
                    </td>
                <?php } else if ($estado_conta == 1) { ?>
                    <td>
                        <a class="btn btn-light my-2 my-sm-0"
                           href="<?= URL::toRoute('user/desbanir', $lista["id_user"]) ?>" role="button">Tirar Ban</a>
                    </td>
                    <?php
                }
            }

            ?>
            </tr>
            <?php
        } else {
            while ($lista = $stmt->fetch(PDO::FETCH_ASSOC)) { ?>

                <tr>
                    <th scope="row"><?= $lista["id_user"] ?></th>
                    <td><?= $lista["username"] ?></td>
                    <?php
                    $estado_conta = $lista["estadoConta"];

                    if ($estado_conta == 0) {

                        ?>
                        <td>
                            <a class="btn btn-dark my-2 my-sm-0"
                               href="<?= URL::toRoute('user/banir', $lista["id_user"]) ?>" role="button">Banir</a>
                        </td>
                    <?php } else if ($estado_conta == 1) { ?>
                        <td>
                            <a class="btn btn-light my-2 my-sm-0"
                               href="<?= URL::toRoute('user/desbanir', $lista["id_user"]) ?>" role="button">Tirar
                                Ban</a>
                        </td>
                        <?php
                    }
                    ?>
                </tr>

                <?php
            }
        }

        } catch (PDOException $e) {
            echo "Error: " . $e->getMessage();
        }
        $conn = null;

        ?>
        </tbody>
    </table>
</div>

<div class="rodape">
    <?php

    Layout::includeLayout('rodape');
    }
    }else{
    View::make('jogo_stb.index');
    }
    }
    ?>
</div>
</body>
</html>