<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Post;

$idUser = Session::has("id_user");

if ($idUser == false) {
    View::make('jogo_stb.login');

}else{

$estadoContaUser = Session::has("tipo_utilizador");

if ($estadoContaUser == true) {
$estadoContaUser2 = Session::get("tipo_utilizador");

if ($estadoContaUser2 == 0){
    View::make('jogo_stb.index');
}else{

    $users = Data::get("users");

Layout::includeLayout('menu');

?>

<div class="search-player justify-content-center">
    <form class="form-inline" method="post" action="<?= Url::toRoute('user/search') ?>">
        <input class="form-control mr-sm-2" name="search" type="text" placeholder="Search">
        <button class="btn btn-dark" type="submit">Search</button>
    </form>
</div>


<div class="players-container">
        <table class="table table-striped">
            <thead class="thead">
            <tr>
                <th scope="col">ID User</th>
                <th scope="col">Username</th>
                <th scope="col">Banir</th>
                <th scope="col">Admin</th>
            </tr>
            </thead>
            <tbody class="tbody">
            <?php foreach ($users as $user) { ?>
                <tr>
                    <td><?=$user->id_user?></td>
                    <td><?=$user->username?></td>
                    <td>
                        <?php
                        if ($user->estadoconta == 0){ ?>
                            <a href="<?=Url::toRoute('user/banuser', $user->id_user)?>" class="btn btn-dark my-2 my-sm-0" role="button">Banir</a>
                        <?php
                        }
                        else if ($user->estadoconta == 1){ ?>
                            <a href="<?=Url::toRoute('user/tirarban', $user->id_user)?>" class="btn btn-light my-2 my-sm-0" role="button">Tirar Ban</a>
                        <?php
                        }
                        ?>

                    </td>
                    <td>
                        <?php
                        if ($user->tipouser == 0){ ?>
                            <a href="<?=Url::toRoute('user/tornaradmin', $user->id_user)?>" class="btn btn-warning my-2 my-sm-0" role="button">Tornar Admin</a>
                            <?php
                        }
                        else if ($user->tipouser == 1){ ?>
                            <a href="<?=Url::toRoute('user/removeradmin', $user->id_user)?>" class="btn btn-outline-warning tadmin my-2 my-sm-0" role="button">Remover Admin</a>
                            <?php
                        }
                        ?>

                    </td>
                </tr>
            <?php } ?>

            </tbody>

        </table>
</div>

<div class="rodape">
    <?php

    Layout::includeLayout('rodape');
    }
    } else {
        View::make('jogo_stb.index');
    }
    }
    ?>
</div>
</body>
</html>