<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;

$idUser = Session::has("id_user");

if ($idUser == false) {
    View::make('jogo_stb.login');
}else{

Layout::includeLayout('menu');

$servername = "localhost:3308";
$username = "root";
$password = "";
$dbname = "shutthebox";

try {
$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


$stmt = $conn->prepare("SELECT * FROM  users");
$stmt->execute();
?>

<div class="search-player justify-content-center">
    <form class="form-inline" action="/action_page.php">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-dark" type="submit">Search</button>
    </form>
</div>

<div class="players-container">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col">ID User</th>
            <th scope="col">Username</th>
            <th scope="col">Banir</th>
        </tr>
        </thead>
        <tbody class="tbody">
        <?php
        $i = 1;
        while ($lista = $stmt->fetch(PDO::FETCH_ASSOC)) { ?>

        <tr>
            <th scope="row"><?= $lista["id_user"] ?></th>
            <td><?= $lista["username"] ?></td>
            <td>
                <a class="btn btn-dark my-2 my-sm-0" href="<?= URL::toRoute('user/banir', $lista["id_user"]) ?>" role="button">Banir</a>
            </td>
        </tr>
            <?php $i += 1;
        }\Tracy\Debugger::barDump($lista["userM"], "username" );

        } catch (PDOException $e) {
            echo "Error: " . $e->getMessage();
        }
        $conn = null;

        ?>
        </tbody>
    </table>
</div>

<div class="rodape">
    <?php

    Layout::includeLayout('rodape');
    }
    ?>
</div>
</body>
</html>