<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('menu');

$gameEngine = Data::get('ge');

?>
<?php
if ($gameEngine->getEstadoJogo() == 5) {

    $totalP1 = $gameEngine->tabuleiro->checkFinalJogadaP1($gameEngine->tabuleiro->numerosBloqueioP1->getNumerosBloqueio());
    $totalP2 = $gameEngine->tabuleiro->checkFinalJogadaP2($gameEngine->tabuleiro->numerosBloqueioP2->getNumerosBloqueio());

    if ($totalP1 > $totalP2) {
        $winner = "Jogador 2";
    } else if ($totalP1 < $totalP2) {
        $winner = "Jogador 1";
    } else if ($totalP1 == $totalP2) {
        $winner = "Empate";
    }
    ?>
    <div class="card-body pontuacao">
        <h5 class="card-title">Pontuação P1 </h5>
        <p class="card-text"> <?= $totalP1 ?> Pontos</p>
        <h5 class="card-title">Pontuação P2 </h5>
        <p class="card-text"> <?= $totalP2 ?> Pontos</p>
        <h5 class="card-title">VENCEDOR </h5>
        <p class="card-text"> <?= $winner ?> </p>

            <a type="button" href="<?= URL::toRoute('jogo/game') ?>"
               class="btn btn-outline-secondary">Iniciar novo Jogo</a>

    </div>

    <?php
}
?>


<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="container card">
                <div class="row">
                    <div class="col">
                        <?php

                        if ($gameEngine->getEstadoJogo() != 2) {
                            $numerosBloqueadosP1 = $gameEngine->tabuleiro->numerosBloqueioP1->getNumerosBloqueio();
                            \Tracy\Debugger::barDump($numerosBloqueadosP1);
                            for ($i = 1; $i <= 9; $i++) {
                                if ($numerosBloqueadosP1[$i] == false) {
                                    ?>
                                    <a class="btn btn-primary" role="button"><?= $i ?></a>
                                    <?php
                                } else { ?>
                                    <a class="btn btn-primary checked" role="button"><?= $i ?></a>
                                    <?php
                                }
                            }
                        }
                        if ($gameEngine->getEstadoJogo() == 2) {
                            $numerosBloqueadosP1 = $gameEngine->tabuleiro->numerosBloqueioP1->getNumerosBloqueio();
                            \Tracy\Debugger::barDump($numerosBloqueadosP1);
                            for ($i = 1; $i <= 9; $i++) {
                                if ($numerosBloqueadosP1[$i] == false) {
                                    ?>
                                    <a href="<?= URL::toRoute('jogo/seleciona', $i) ?>" class="btn btn-primary"
                                       role="button"><?= $i ?></a>
                                    <?php
                                } else { ?>
                                    <a class="btn btn-primary checked" role="button"><?= $i ?></a>
                                    <?php
                                }
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="dados">
                    <?php
                    if ($gameEngine->getEstadoJogo() == 2 || $gameEngine->getEstadoJogo() == 4) {
                        \Tracy\Debugger::barDump($gameEngine); ?>

                        <?php
                        if ($gameEngine->tabuleiro->resultadoDado1 == 1) { ?>
                            <img src="<?= Asset::image('dice_r_1.png') ?>" alt="logo" style="width:40px;">
                            <?php
                        } else if ($gameEngine->tabuleiro->resultadoDado1 == 2) { ?>
                            <img src="<?= Asset::image('dice_r_2.png') ?>" alt="logo" style="width:40px;">
                            <?php
                        } else if ($gameEngine->tabuleiro->resultadoDado1 == 3) { ?>
                            <img src="<?= Asset::image('dice_r_3.png') ?>" alt="logo" style="width:40px;">
                        <?php } else if ($gameEngine->tabuleiro->resultadoDado1 == 4) { ?>
                            <img src="<?= Asset::image('dice_r_4.png') ?>" alt="logo" style="width:40px;">
                            <?php
                        } else if ($gameEngine->tabuleiro->resultadoDado1 == 5) { ?>
                            <img src="<?= Asset::image('dice_r_5.png') ?>" alt="logo" style="width:40px;">
                            <?php
                        } else if ($gameEngine->tabuleiro->resultadoDado1 == 6) { ?>
                            <img src="<?= Asset::image('dice_r_6.png') ?>" alt="logo" style="width:40px;">
                            <?php
                        }
                        if ($gameEngine->tabuleiro->resultadoDado2 == 1) { ?>
                            <img src="<?= Asset::image('dice_w_1.png') ?>" alt="logo" style="width:40px;">
                        <?php } else if ($gameEngine->tabuleiro->resultadoDado2 == 2) { ?>
                            <img src="<?= Asset::image('dice_w_2.png') ?>" alt="logo" style="width:40px;">
                        <?php } else if ($gameEngine->tabuleiro->resultadoDado2 == 3) { ?>
                            <img src="<?= Asset::image('dice_w_3.png') ?>" alt="logo" style="width:40px;">
                        <?php } else if ($gameEngine->tabuleiro->resultadoDado2 == 4) { ?>
                            <img src="<?= Asset::image('dice_w_4.png') ?>" alt="logo" style="width:40px;">
                        <?php } else if ($gameEngine->tabuleiro->resultadoDado2 == 5) { ?>
                            <img src="<?= Asset::image('dice_w_5.png') ?>" alt="logo" style="width:40px;">
                        <?php } else if ($gameEngine->tabuleiro->resultadoDado2 == 6) { ?>
                            <img src="<?= Asset::image('dice_w_6.png') ?>" alt="logo" style="width:40px;">
                        <?php }

                        if ($gameEngine->getEstadoJogo() == 2) {
                            ?>
                            <div class="acabar-jogo">
                                <a type="button" href="<?= URL::toRoute('jogo/fimP1') ?>"
                                   class="btn btn-outline-secondary">Acabar Jogo - P1</a>
                            </div>
                            <?php
                        } else if ($gameEngine->getEstadoJogo() == 4) { ?>
                            <div class="acabar-jogo">
                                <a type="button" href="<?= URL::toRoute('jogo/fimP2') ?>"
                                   class="btn btn-outline-secondary">Acabar Jogo - P2</a>
                            </div>
                            <?php
                        }
                    }
                    if ($gameEngine->getEstadoJogo() == 1 || $gameEngine->getEstadoJogo() == 3) { ?>
                        <div class="rodar-dado">
                            <a type="button" href="<?= URL::toRoute('jogo/rodarDados') ?>"
                               class="btn btn-outline-secondary">Rodar Dados</a>
                        </div>
                    <?php }
                    ?>
                </div>
            </div>


            <div class="col-sm">
                <div class="container card">
                    <div class="row">
                        <?php

                        if ($gameEngine->getEstadoJogo() != 4) {

                            $numerosBloqueadosP2 = $gameEngine->tabuleiro->numerosBloqueioP2->getNumerosBloqueio();
                            \Tracy\Debugger::barDump($numerosBloqueadosP2, "GameEngine");
                            for ($i = 1; $i <= 9; $i++) {
                                if ($numerosBloqueadosP2[$i] == false) {
                                    ?>
                                    <a class="btn btn-primary" role="button"><?= $i ?></a>
                                    <?php
                                } else { ?>
                                    <a class="btn btn-primary checked-p2" role="button"><?= $i ?></a>
                                    <?php
                                }
                            }
                        }
                        if ($gameEngine->getEstadoJogo() == 4) {

                            $numerosBloqueadosP2 = $gameEngine->tabuleiro->numerosBloqueioP2->getNumerosBloqueio();
                            \Tracy\Debugger::barDump($numerosBloqueadosP2);
                            for ($i = 1; $i <= 9; $i++) {
                                if ($numerosBloqueadosP2[$i] == false) {
                                    ?>
                                    <a href="<?= URL::toRoute('jogo/selecionaP2', $i) ?>" class="btn btn-primary"
                                       role="button"><?= $i ?></a>
                                    <?php
                                } else { ?>
                                    <a class="btn btn-primary checked" role="button"><?= $i ?></a>
                                    <?php
                                }
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>

        </div>
        <div class="rodape">
            <?php Layout::includeLayout('rodape'); ?>
        </div>

