<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('menu-index'); ?>


<div class="container-index">
    <img src="<?= Asset::image('logo_stb_login.png')?>" alt="logo" style="width:100px;">
    <span class="title-index">Shut The Box</span>
    <a class="btn btn-primary" type="button" href="<?= URL::toRoute('jogo/login')?>">START GAME</a>
</div>
<div class="rodape">
    <?php Layout::includeLayout('rodape'); ?>
</div>

