<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('menu');

try {
    $estado = Data::get('estado');

}
catch (Exception $ex) {
    $estado = false;
}

if($estado == "bloqueado"){
    echo '<script type="text/javascript">';
    echo 'alert("ERRO! Esta conta foi bloqueada!")';
    echo '</script>';
}
elseif ($estado == "erro"){
    echo '<script type="text/javascript">';
    echo 'alert("ERRO! Email ou password incorretos!")';
    echo '</script>';
}

?>

<div class="modal-dialog modal-login">
    <div class="modal-content">
        <div class="modal-header">
            <img src="<?= Asset::image('logo_stb_login.png')?>" alt="logo" style="width:100px;">
        </div>
        <h4 class="modal-title">Login</h4>
        <div class="modal-body">
            <form action="<?=Url::toRoute('user/login')?>" method="post">
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="email" class="form-control" name="email" placeholder="Email" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock"></i>
                    <input type="password" class="form-control" name="password" placeholder="Palavra Passe" required="required">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Iniciar Sessão">
                </div>
            </form>
        </div>
    </div>
</div>

<div class="rodape">
    <?php Layout::includeLayout('rodape'); ?>
</div>