<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;

$idUser = Session::has("id_user");

if ($idUser == false) {
    View::make('jogo_stb.login');
}else{

Layout::includeLayout('menu');

$servername = "localhost:3308";
$username = "root";
$password = "";
$dbname = "shutthebox";

try {
$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


$stmt = $conn->prepare("SELECT p.pontos, u.username FROM pontos p JOIN users u ON p.users_id_user = u.id_user 
ORDER BY p.pontos ASC LIMIT 5");
$stmt->execute();
?>
<div class="alterar-registo">
    <a class="btn btn-dark" href="<?= URL::toRoute('user/editar_reg')?>" role="button">Editar Registo</a>
</div>
<div class="players-container">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col"> TOP 10</th>
            <th scope="col"> Nº Jogador: <?= Session::get("id_user"); ?></th>
        </tr>
        <tr>
            <th scope="col">Jogo</th>
            <th scope="col">Pontuação</th>
        </tr>
        </thead>
        <tbody class="tbody">
        <?php
        $i = 1;
        while ($lista = $stmt->fetch(PDO::FETCH_ASSOC)) { ?>

            <tr>
                <th scope="row"><?= $i ?></th>
                <td><?= $lista["pontos"] ?></td>
            </tr>
            <?php $i += 1;
        }\Tracy\Debugger::barDump($lista["userM"], "username" );

        } catch (PDOException $e) {
            echo "Error: " . $e->getMessage();
        }
        $conn = null;

        ?>
        </tbody>
    </table>
</div>

<div class="rodape">
    <?php Layout::includeLayout('rodape');
    }?>
</div>
