<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use ArmoredCore\WebObjects\Data;

$idUser = Session::has("id_user");

if ($idUser == false) {
    View::make('jogo_stb.login');
}else{

$scores = Data::get("scoresuser");
\Tracy\Debugger::barDump($scores, "score 1");

$rank = 0;
Layout::includeLayout('menu');

?>
<div class="alterar-registo">
    <a class="btn btn-dark" href="<?=Url::toRoute('user/edit', Session::get("id_user"))?>" role="button">Editar Registo</a>
</div>
<div class="players-container">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col">Classificação</th>
            <th scope="col">Pontuação</th>
        </tr>
        </thead>
        <tbody class="tbody">
        <?php
        foreach ($scores as $score) {
            $rank += 1;
            ?>
            <tr>
                <td><?=$rank?></td>
                <td><?=$score->pontos?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<div class="rodape">
    <?php Layout::includeLayout('rodape');
    }?>
</div>
