<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('menu'); ?>
<div class="alterar-registo">
    <a class="btn btn-dark" href="<?= URL::toRoute('jogo/editar_registo')?>" role="button">Editar Registo</a>
</div>
<div class="players-container">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col">Jogo</th>
            <th scope="col">Data</th>
            <th scope="col">Pontuação</th>
        </tr>
        </thead>
        <tbody class="tbody">
        <tr>
            <th scope="row">1</th>
            <td>06/05/2000</td>
            <td>19</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>06/05/2000</td>
            <td>18</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>06/05/2000</td>
            <td>17</td>
        </tr>
        </tbody>
    </table>
</div>

<div class="rodape">
    <?php Layout::includeLayout('rodape'); ?>
</div>
