<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('menu');
try {
    $user = Data::get('registo');
}catch (Exception $ex){
    $user = "";
}

if($user == "passwords_dif"){
    echo '<script type="text/javascript">';
    echo 'alert("ERRO! As passwords não coincidem!")';
    echo '</script>';
}
elseif ($user == "password_curta"){
    echo '<script type="text/javascript">';
    echo 'alert("ERRO! A password é demasiado curta (Min 6 caracteres)!")';
    echo '</script>';
}

elseif ($user == "repetido"){
    echo '<script type="text/javascript">';
    echo 'alert("ERRO! Este utilizador já se encontra registado!")';
    echo '</script>';
}

?>

<div class="modal-dialog modal-login">
    <div class="modal-content">
        <div class="modal-header">
            <img src="<?= Asset::image('logo_stb_login.png')?>" alt="logo" style="width:100px;">
        </div>
        <h4 class="modal-title">Registar</h4>
        <div class="modal-body">
            <form action="<?=Url::toRoute('user/store')?>" name="users" method="post">
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="text" class="form-control" name="username" placeholder="Username" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="text" class="form-control" name="nome" placeholder="Nome" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="email" class="form-control" name="email" placeholder="Email" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock"></i>
                    <input type="password" class="form-control" name="password" placeholder="Palavra Passe" required="required">
                </div>

                <div class="form-group">
                    <i class="fa fa-lock"></i>
                    <input type="password" class="form-control" name="confirm-password" placeholder="Confirmar Palavra Passe" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="date" class="form-control" name="datanasc" required="required">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Registar">
                </div>
            </form>

        </div>
    </div>
</div>

<?php


?>
<div class="rodape">
<?php Layout::includeLayout('rodape'); ?>
</div>