<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('menu'); ?>
<?php $user = Data::get('users');
\Tracy\Debugger::barDump($user);?>


<div class="modal-dialog modal-login">
    <div class="modal-content">
        <div class="modal-header">
            <img src="<?= Asset::image('logo_stb_login.png')?>" alt="logo" style="width:100px;">
        </div>
        <h4 class="modal-title">Registar</h4>
        <div class="modal-body">
            <form action="<?=Url::toRoute('user/store')?>" method="post">
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="text" class="form-control" name="<?=$user->username?>" placeholder="Username" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="text" class="form-control" name="<?=$user->nome?>" placeholder="Nome" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="email" class="form-control" name="<?=$user->email?>" placeholder="Email" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock"></i>
                    <input type="password" class="form-control" name="<?=$user->password?>" placeholder="Palavra Passe" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock"></i>
                    <input type="password" class="form-control" name="" placeholder="Confirmar Palavra Passe" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="date" class="form-control" name="<?=$user->dtaNascimento?>" required="required">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Registar">
                </div>
            </form>

        </div>
    </div>
</div>
<div class="rodape">
<?php Layout::includeLayout('rodape'); ?>
</div>