<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('menu'); ?>

<div class="top10-container">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col">Classificação</th>
            <th scope="col">Username</th>
            <th scope="col">Data</th>
            <th scope="col">Pontuação</th>
        </tr>
        </thead>
        <tbody class="tbody">
        <tr>
            <th scope="row">1</th>
            <td>pedrorolo</td>
            <td>06/05/2000</td>
            <td>19</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>gustavom</td>
            <td>06/05/2000</td>
            <td>18</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>mcarapinha</td>
            <td>06/05/2000</td>
            <td>17</td>
        </tr>
        </tbody>
    </table>
</div>

<?php Layout::includeLayout('rodape'); ?>