<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('menu');

    $scores = Data::get("scores");
    //\Tracy\Debugger::barDump($scores, "score");

$rank = 0;
?>

<div class="top10-container">
    <table class="table table-striped">
        <thead class="thead">
        <tr>
            <th scope="col">Classificação</th>
            <th scope="col">Username</th>
            <th scope="col">Pontuação</th>
        </tr>
        </thead>
        <tbody class="tbody">
        <?php
        foreach ($scores as $score) {
            $rank += 1;

            ?>
            <tr>
                <td><?=$rank?></td>
                <td><?=$score->users_id_user ?></td>
                <td><?=$score->pontos?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<div class="rodape">
    <?php Layout::includeLayout('rodape'); ?>
</div>