<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('menu');

$servername = "localhost:3308";
$username = "root";
$password = "";
$dbname = "shutthebox";

try {
$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);


$stmt = $conn->prepare("SELECT p.pontos, u.username FROM pontos p JOIN users u ON p.users_id_user = u.id_user 
ORDER BY pontos ASC LIMIT 10");
$stmt->execute();


?>

<div class="top10-container">
    <table class="table">
        <thead class="thead">
        <tr>
            <th scope="col">Classificação</th>
            <th scope="col">Username</th>
            <th scope="col">Pontuação</th>
        </tr>
        </thead>
        <tbody class="tbody">

        <?php
        $i = 1;
        while ($lista = $stmt->fetch(PDO::FETCH_ASSOC)) { ?>

        <tr>
            <th scope="row"><?= $i ?></th>
            <td><?= $lista["username"] ?></td>
            <td><?= $lista["pontos"] ?></td>

        </tr>
        <?php $i += 1;
        }\Tracy\Debugger::barDump($lista["userM"], "username" );

        } catch (PDOException $e) {
            echo "Error: " . $e->getMessage();
        }
        $conn = null;

        ?>
        </tbody>
    </table>
</div>

<div class="rodape">
    <?php Layout::includeLayout('rodape'); ?>
</div>