<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$idUser = Session::has("id_user");

if ($idUser == false) {
    View::make('jogo_stb.login');
}else{

Layout::includeLayout('menu');

$user = Data::get('user');
\Tracy\Debugger::barDump($user, "update");
?>
<div class="modal-dialog modal-login">
    <div class="modal-content">
        <div class="modal-header">
            <img src="<?= Asset::image('logo_stb_login.png')?>" alt="logo" style="width:100px;">
        </div>
        <h4 class="modal-title">Editar Registo</h4>
        <div class="modal-body">
            <form action="<?=Url::toRoute('user/update', Session::get("id_user"))?>" method="post">
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="text" class="form-control" name="nome" placeholder="Nome" value="<?= $user->nome ?>" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="email" class="form-control" name="email" placeholder="Email" value="<?= $user->email ?>" required="required">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock"></i>
                    <input type="password" class="form-control" name="password" placeholder="Palavra Passe">
                </div>
                <div class="form-group">
                    <i class="fa fa-lock"></i>
                    <input type="password" class="form-control" name="confirm-password" placeholder="Confirmar Palavra Passe">
                </div>
                <div class="form-group">
                    <i class="fa fa-user"></i>
                    <input type="date" class="form-control" value="<?= $user->dtanascimento ?>" name="dtanascimento" required="required">
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Editar Registo">
                </div>
            </form>

        </div>
    </div>
</div>
<div class="rodape">
    <?php Layout::includeLayout('rodape');
    }?>
</div>
